# Generated by Django 5.2.5 on 2025-08-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_userinfo_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='diet_description',
            field=models.TextField(blank=True),
        ),
    ]
