# Generated by Django 5.2.5 on 2025-08-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_userinfo_diet_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
