# Generated by Django 5.2.5 on 2025-08-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dietInfo',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Diet',
        ),
    ]
