# Generated by Django 5.2.5 on 2025-08-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0006_user_dietinfo_delete_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apiKey',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
